language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud: 
   organization: "dzigen"
   token:
    secure: "fOKt9sXoNeuhGc2RkuFMEABi7RhQqDvRGtJ4KmGaKIk0ZDW5Ds9MyWLNPKPgc+Y5LmVHPdIOL+hiBnfS6N0o6CWcy39wF7Gyxh9Ug7nDzmqY7RulWmFKWApPbQ6CyQ6PayFKdS7G0GaBhrNsOZ6O98Khd3tdj+noYwPNZNpxJ3urDYJZedtODrLLNA18i8v9vAyYh0maTV1NKRhco1m/wu0bb/kd7NyPaTZ3yv58wfMXUHSY+5ieMehR1j+8bhcjwrEqOsNrPCFwSm9Ev+3CxRJL3kMfy6lnNBe7RTQMgbWHkXo8Al3BgSaM1v8xmQ/2EUFlO8Sgofcme7XKKL/ZAjOWLKyP0QXWuLqAhYGtKmic3ixQkBSdw/eL//QCCbyUpxGZHJyhtZQ7Tn6R3pv5II2PZkVTIsBX2cDs0LuzTozV1bG67RGiUeZIynQE9hXZp1yxoI1KZt7161KIz1RSgg1K2ODi6NKP2taSCjnTZaHD9E5KwK4XPCDf5fnFIBy+aQJ6tIu3PE2NLhtO6Ih0KWvFAdZqSNOA+wY6EnxDCMnB5KvFqDAb9Uql45BVDQJIKlcDHQIHFVHKyz8ShUoy05h0a407nRLX8kCssTFHH8Cf8XP2IfgpNznl7hvrVHNMAJyA567ZAjSVJw6OF7dwJNLKN3Y2yf4fYDsIS73bx0A=" 

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:
  directories:
  - "$HOME/.sonar/cache"

notifications:
  email: false