language:
  - cpp

before_install:
  - pip install --user cpp-coveralls

addons:
  sonarcloud: 
   organization: "dzigen"
   token:
    secure:"YrFNEeKtS7JDUB7NEoMoZqlOIbbtEGKGtf4JCABtzuD1CabHuB9yH0AjEFPky/3BAgMmupcqqHI0PcPEFky+dOkPN5TV0bEk4M3zyAE43830ZPYb0vaGALliotpnLYvr+dDROInYQW2o6YMHIwXFzY9/SWYNjW3zKwSxolFQjfWWkjvwYFqf4mvXZlqHQmbqqVo9Ohc1zZQA5L9YL0o5WhafnZYUL6v0mL1bxHyiERe2FqpV7FOb8s4BqXRogJ2QjcSxw4pzxj7cHkvNqqVrhWS3b6bCiTku5W+6NkZct7JLZhENsxtR22LB5fARwwfx1g3E0X370Nk+lrnv7UfbBEXZAT+VNLp21WdxA+5zq0PDkA3aqjZXTbhIcq8O1Cqrd3UzKbdLAMtk6jdJM5JaNylBY/S/j04koJ41WE1sAkOwqbSBwdoUdB70Mg7omgVNtsVVqkROejZqXxmsBbfyHj9K7y5YOl2Z8BMdcjRhmEXMm10BpsKp3avtSmMvaaAscjwHzTs/gUQFCO+LQPVfMkSUbUKT6GgpajeGXi1GDybXtpD7BkDNRFr54WLC805i62KtyWrDwc7EeS/9jyNvJljJgNQfVIcBHvxJYrTvMCleXsntUzyrFIP34Myg4JkFMrr//koI7W5aVypM8d6rPmjCUQ9WJRq8MBLzpV1o0D8=" 

script:
  - qmake
  - make
  - ./tests/tests

after_success:
  - coveralls --root . -E ".*external.*" -E ".*tests.*"
  - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
  - sonar-scanner -Dsonar.cfamily.build-wrapper-output=bw-output

cache:
  directories:
  - "$HOME/.sonar/cache"

notifications:
  email: false